services:
    feneck91.introduciator.controller.acp_general:
        class: feneck91\introduciator\controller\acp_general_controller
        arguments:
            - '%core.php_ext%'
            - '@language'
            - '@request'
            - '@template'
            - '@user'
            - '@config'

    feneck91.introduciator.controller.acp_configuration:
        class: feneck91\introduciator\controller\acp_configuration_controller
        arguments:
            - '@feneck91.introduciator.helper'
            - '@dbal.conn'
            - '@log'
            - '%core.table_prefix%'
            - '%core.root_path%'
            - '%core.php_ext%'
            - '@language'
            - '@request'
            - '@template'
            - '@user'
            - '@config'

    feneck91.introduciator.controller.acp_explanation:
        class: feneck91\introduciator\controller\acp_explanation_controller
        arguments:
            - '@feneck91.introduciator.helper'
            - '@dbal.conn'
            - '@log'
            - '%core.table_prefix%'
            - '%core.root_path%'
            - '%core.php_ext%'
            - '@language'
            - '@request'
            - '@template'
            - '@user'
            - '@config'

    feneck91.introduciator.controller.acp_statistics:
        class: feneck91\introduciator\controller\acp_statistics_controller
        arguments:
            - '@feneck91.introduciator.helper'
            - '@dbal.conn'
            - '@pagination'
            - '%core.table_prefix%'
            - '%core.root_path%'
            - '%core.php_ext%'
            - '@language'
            - '@request'
            - '@template'
            - '@user'
            - '@config'
            